# for calculator
DIGITS = '0123456789'
POINT = '.'
UNARY_OPERATORS = '+-'
OPERATION_SYMBOLS = '+-*/'

# for converter
LENGTH = ['mm', 'cm', 'm', 'km']
WEIGHT = ['g', 'kg']
TEMPERATURE = ['c', 'k', 'f']
G_TO_KG_SCALE = 1000
KELVIN_OFFSET = 273.15
C_TO_F_SCALE = 1.8
FAHRENHEIT_OFFSET = 32
ABS_ZERO_FAHRENHEIT = -459.67
ABS_ZERO_KELVIN = 0